# Generated by Django 5.0.2 on 2024-02-12 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/')),
                ('processing', models.BooleanField(default=False)),
                ('processingSuccess', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
